version: '3'

services:
  camunda:
    image: camunda/camunda-bpm-platform:tomcat-7.8.0-alpha5
    depends_on:
       - db
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_URL=jdbc:mysql://db:3306/process-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    volumes:
      - webapps:/camunda/webapps
    links:
      - db
    ports:
      - "8080:8080"
    restart: always

  db:
    image: mysql
    volumes:
       - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=camunda
      - MYSQL_USER=camunda
      - MYSQL_PASSWORD=camunda
      - MYSQL_DATABASE=process-engine
    restart: always
volumes:
    webapps:
    db_data:
